title: Site

tabs: 
  landing:
    label: Pages
    sections:
      pages:
        create: false
        type: pages
        query: site.pages.listed

  events:
    sections:
      events:
        label: Events
        type: pages
        parent: page("Events")
        layout: cards
        template: event
        create: event
        ratio: 3/4
        image:
          cover: true

  info:
    label: Museum Info
    columns:
      home:
        type: fields
        fields: 
          intro_txt:
            label: Text displayed in homepage
            type: textarea
            size: medium
      address:
        width: 1/2
        type: fields
        fields:
          address:
            type: textarea
            size: small
      times:
        width: 1/2
        type: fields
        fields:
          opening_hours:
            type: textarea
            size: small

  privacy:
    label: Privacy
    sections:
      privacy:
        create: false
        type: pages
        query: site.pages.filterBy('title','*=','policyn')

     

