title: Site

tabs: 
  landing:
    label: Pages
    sections:
      pages:
        create: false
        type: pages
        query: site.pages.listed

  homepage:
    label: Homepage
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: small
          related:
            label: Events to display in home
            type: pages
            translate: false
            flip: true
            query: site.find('events').children.filterBy('eventStateInTime', '==', 'ended')

  events:
    sections:
      events:
        label: Events
        type: pages
        parent: page("Events")
        template: event
        create: event
        search: true
        layout: cards
        size: small
        sortby: date desc
        flip: true
        limit: 50
        ratio: 3/4
        image:
          cover: true

  info:
    label: Museum Info
    columns:
      address:
        width: 1/2
        type: fields
        fields:
          address:
            type: textarea
            size: small
      times:
        width: 1/2
        type: fields
        fields:
          opening_hours:
            type: textarea
            size: small

  privacy:
    label: Minor pages
    sections:
      privacy:
        type: pages
        template: default
        query: site.pages.unlisted.filterBy('title','!=','Home').filterBy('title','!=','Events').filterBy('title','!=','Sök').filterBy('title','!=','Error').filterBy('title','!=','site')

     

