title: Site

tabs: 
  landing:
    sections:
      pages:
        create: false
        type: pages
        query: site.pages.listed

  events:
    sections:
      events:
        label: Events
        type: pages
        parent: page("Events")
        layout: cards
        template: event
        create: event
        ratio: 3/4
        image:
          cover: true

  info:
    columns:
      address:
        width: 1/2
        type: fields
        fields:
          address:
            type: textarea
            size: small
      times:
        width: 1/2
        type: fields
        fields:
          opening_hours:
            type: textarea
            size: small

     

