title: Site

tabs: 
  landing:
    label: Pages
    sections:
      pages:
        create: false
        type: pages
        query: site.pages.listed

  homepage:
    label: Homepage
    sections:
      homefields:
        type: fields
        fields:
          text:
            type: textarea
            size: small
          related:
            label: Events to display in home
            type: pages
            translate: false
            flip: true
            query: site.find('events')
            info: "{{ page.starting_date.toDate('d-m-Y')}} {{ page.ending_date.toDate('d-m-Y') }}"
            # info: "{{ page.eventStateInTime}}"

  events:
    sections:
      events:
        label: Events
        type: pages
        parent: page("Events")
        template: event
        create: event
        search: true
        layout: cards
        size: small
        sortby: date desc
        flip: true
        limit: 50
        ratio: 3/4
        image:
          cover: true

  pdfarchive:
    label: Archive
    sections:
      fields:
        type: fields
        fields:
          archivetext:
            type: textarea
            size: small
      pdfarchive:
        label: PDF Archive
        type: pages
        parent: site.index.findBy("intendedTemplate", "pdfarchive")
        template: catalogue
        create: catalogue
        search: true
        layout: list
        sortby: date desc
        limit: 50
  info:
    label: Museum Info
    columns:
      address:
        width: 1/2
        type: fields
        fields:
          address:
            type: textarea
            size: small
      times:
        width: 1/2
        type: fields
        fields:
          opening_hours:
            type: textarea
            size: small

  privacy:
    label: Minor pages
    sections:
      privacy:
        type: pages
        # template: default
        query: site.pages.unlisted.filterBy('title','!=','Home').filterBy('title','!=','Events').filterBy('title','!=','Sök').filterBy('title','!=','Error').filterBy('title','!=','site')

     

